[build]
  command = "pip install -r requirements.txt && mkdir -p netlify/functions/api && cp -r . netlify/functions/api"
  functions = "netlify/functions"
  publish = "public"

[dev]
  framework = "#custom"
  targetPort = 8000  # Match your FastAPI port
  port = 8888
  publish = "public"
  command = "uvicorn api:app --reload --port 8000"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/api/"
  status = 200